-- Add missing columns to cards table for bulk upload & store display
ALTER TABLE cards ADD COLUMN IF NOT EXISTS base TEXT;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS refundable BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS has_phone BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS has_email BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS cc_data TEXT;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE cards ADD COLUMN IF NOT EXISTS cc_number TEXT;
